### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by KaiTechTips** [edgarssults/FitNote#1]
Hi. I loved the app. Could u maybe add PowerPoint fitbit edition or add image support to onenote cos I wanna sync my timetable.
Thx

**Comment by edgarssults** [comment]
Thanks, I still have to fix the login expiry in FitNote, then it should be better. You'll see the error when you next try to sync.

I'll see what I can do about images, it should theoretically be possible, but the Fitbit API is fairly limited regarding UI. It is not built for dynamically adding UI elements like images and text, that's why I have a limit of 50 lines per note.

Regarding Powerpoint, I'll read up on what the Microsoft Graph API provides for it, but I think the screen is too small to be usable.

**Comment by Moaske** [comment]
Hi! I've been waiting for ages for a Microsoft Notes application to appear on Fitbit to the point that I started searching how tap into the Notes myself. And just then I found your FitNotes app and it looks very promising.

The actual thing I was looking  to do, was build a Sticky Notes app (to be found in OneNote as well if I'm correct) for my Versa.
I have very low coding experience, but would you be willing to cooperate on this?

Hope to hear from you :)

**Comment by edgarssults** [comment]
> The actual thing I was looking to do, was build a Sticky Notes app (to be found in OneNote as well if I'm correct) for my Versa.
> I have very low coding experience, but would you be willing to cooperate on this?

I had a look and I couldn't find a public API for the Sticky Notes app. Without this you won't be able to access them.

The mobile version of the OneNote app shows sticky notes, but they seem to be using a private API.

**Comment by Moaske** [comment]
> > The actual thing I was looking to do, was build a Sticky Notes app (to be found in OneNote as well if I'm correct) for my Versa.
> > I have very low coding experience, but would you be willing to cooperate on this?
> 
> I had a look and I couldn't find a public API for the Sticky Notes app. Without this you won't be able to access them.
> 
> The mobile version of the OneNote app shows sticky notes, but they seem to be using a private API.

Hi, thanks for your reply 😊
There also happens to be a Web version of Sticky Notes at www.onenote.com/stickynotes
Would it be possible to figure something out from there?

**Comment by KaiTechTips** [comment]
Hi. How about we make a seperate microsoft notes app for the fitbit.
Mabye like the windows sticky notes app.

**Comment by edgarssults** [comment]
> Hi. How about we make a seperate microsoft notes app for the fitbit.
> Mabye like the windows sticky notes app.

There's something like that already: https://gallery.fitbit.com/details/5892c657-e46a-46de-bfb9-46f05c7c7293
There's also an app that syncs your Google Drive docs: https://gallery.fitbit.com/details/d40bd032-d5da-4a40-8d72-09e8d3a141f1

**Comment by edgarssults** [comment]
> There also happens to be a Web version of Sticky Notes at [www.onenote.com/stickynotes](http://www.onenote.com/stickynotes)
> Would it be possible to figure something out from there?

Without a public API it would be really difficult, I don't really want to spend that much time on it.

**Comment by edgarssults** [comment]
I've investigated and it looks like it would be too much of a hassle for me to properly support image sync. Closing this, sorry.
