### ISSUE TITLE
Not able to log in with school/workmail on FitBit Versa 2

### ISSUE THREAD

**Issue by Mohje** [edgarssults/FitNote#14]
Hi,

Downloaded your FitNote app to FitBit Versa 2 couple of days ago, but I am not able to log in. Tried several times. Is it just for personal accounts? I am using OneNote with my univeristy/school-mail, but tha app says it doesn’t exist. Also tried with my work-mail. Both Microsoft mails. 

Best wishes, Mona:-)

**Comment by edgarssults** [comment]
Yes, it only supports personal Microsoft accounts.
