### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by azguy32** [edgarssults/FitNote#18]
Why does this not sync on its own. This app is absolutely pointless if you have to log into your phone to sync notes.

**Comment by edgarssults** [comment]
I know, it's a limitation of how the Fitbit software works and how the Microsoft Graph API behaves.

**Comment by password-1-2-3** [comment]
> Why does this not sync on its own. This app is absolutely pointless if you have to log into your phone to sync notes.



> Why does this not sync on its own. This app is absolutely pointless if you have to log into your phone to sync notes.
https://drive.google.com/drive/folders/17qKVPjjyB0isSO69Y9H8aYOxqszvnbLy

**Comment by password-1-2-3** [comment]
Tap on a clip to paste it in the text box.

**Comment by edgarssults** [comment]
App has been discontinued.

**Comment by edgarssults** [comment]
App has been discontinued.
